spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 220320
    url: jdbc:postgresql://localhost:5432/security_jwt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Jwt data config
jwt:
  url: '\authorization'
  header: 'Authorization'
  prefix: 'Bearer '
  expiration: 120
  secret: '404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970'

